# Generated by Django 5.2.3 on 2025-06-22 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrier',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carrier',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
