# Generated by Django 5.2.3 on 2025-06-22 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_carrier_latitude_alter_carrier_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrier',
            name='address',
        ),
        migrations.RemoveField(
            model_name='carrier',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='carrier',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='carrier',
            name='vehicle_capacity',
        ),
        migrations.RemoveField(
            model_name='carrier',
            name='vehicle_type',
        ),
        migrations.RemoveField(
            model_name='carrier',
            name='vehicle_volume',
        ),
    ]
